services:
  gitea:
    image: gitea/gitea:nightly-linux-amd64
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - '3000:3000'
      - '222:22'
    volumes:
      - gitea-data:/data
  jenkins:
    build: ./jenkins/
    restart: on-failure
    ports:
      - '8081:8080'
      - '50000:5000'
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add: 
      - '998'

volumes:
  gitea-data:
  jenkins-data:
